#### Tejaswee mandlik

## Iris Flower classification

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Load the dataset

In [2]:
data = pd.read_csv(r"C:\Users\Dattatraya\Downloads\archive (1)\Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

###  Display the first few rows of the dataset

In [3]:
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [4]:
# Features (sepal and petal measurements)
X = data.drop('Species', axis=1)

# Labels (species)
y = data['Species']
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [5]:
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

###  Split the data into training and testing sets

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform on training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform on testing data
X_test_scaled = scaler.transform(X_test)


In [8]:
X_train_scaled

array([[-1.21030717, -1.47393679,  1.22037928, -1.5639872 , -1.30948358],
       [-1.37240188, -0.13307079,  3.02001693, -1.27728011, -1.04292204],
       [-0.21458252,  1.08589829,  0.09560575,  0.38562104,  0.28988568],
       [-1.46502743, -1.23014297,  0.77046987, -1.21993869, -1.30948358],
       [-0.74717943, -1.7177306 ,  0.32056046, -1.39196294, -1.30948358],
       [ 1.66108484,  0.59831066, -1.25412249,  0.72966956,  0.95628954],
       [-0.53877194,  0.72020757,  0.32056046,  0.44296246,  0.42316645],
       [-1.09452523, -0.74255534,  0.99542457, -1.27728011, -1.30948358],
       [-1.62712214, -0.98634915,  1.22037928, -1.33462153, -1.30948358],
       [-0.9787433 , -0.74255534,  2.34515281, -1.27728011, -1.44276436],
       [ 1.56845929, -0.01117388, -0.80421307,  0.78701097,  0.95628954],
       [ 0.24854522,  0.23261993,  0.77046987,  0.44296246,  0.55644722],
       [ 0.27170161,  1.08589829,  0.09560575,  0.5576453 ,  0.42316645],
       [-1.34924549, -0.49876152,  1.8

In [9]:
X_test_scaled

array([[-0.02933142,  0.35451684, -0.57925837,  0.5576453 ,  0.02332414],
       [-1.30293272, -0.13307079,  1.67028869, -1.16259727, -1.17620281],
       [ 1.012706  ,  2.30486738, -1.02916778,  1.81915651,  1.48941263],
       [ 0.08645051,  0.23261993, -0.35430366,  0.44296246,  0.42316645],
       [ 0.04013774,  1.2077952 , -0.57925837,  0.61498672,  0.28988568],
       [-1.00189969, -0.49876152,  0.77046987, -1.27728011, -1.04292204],
       [-0.23773891, -0.2549677 , -0.35430366, -0.07311031,  0.15660491],
       [ 1.5453029 ,  1.32969211,  0.09560575,  0.78701097,  1.48941263],
       [-0.14511336,  0.47641375, -1.9289866 ,  0.44296246,  0.42316645],
       [ 0.17907606, -0.01117388, -0.80421307,  0.09891395,  0.02332414],
       [ 0.8274549 ,  0.84210448,  0.32056046,  0.78701097,  1.08957031],
       [-1.44187104, -1.23014297, -0.12934896, -1.33462153, -1.44276436],
       [-0.88611775, -0.37686461,  0.99542457, -1.39196294, -1.30948358],
       [-1.5113402 , -1.10824606,  0.0

###  Initialize the KNN classifier

In [10]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier

KNeighborsClassifier(n_neighbors=3)

In [11]:
# Train the classifier on scaled training data
knn_classifier.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

###  Make predictions on scaled testing data

In [12]:
y_pred = knn_classifier.predict(X_test_scaled)
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

###  Calculate accuracy

In [13]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [14]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=10,random_state=6,shuffle=True)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=3)

In [16]:
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
y_pred = clf.predict(X_test)
print(y_pred)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


In [18]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)